### ISSUE TITLE
[BUG] the extension create a rollback on intellisense suggestions

### ISSUE THREAD

**Issue by GauthierPoulain** [Etheram68/Header101-Vscode#10]
**Description of the bug**
the extension create a rollback on intellisense suggestions

**To Reproduce**
```
1. enable autosave
2. type something
3. quickly change selection in suggestions
4. See error
```
**Expected behavior**
the selection will go back to the top when the autosave will be done and the header will be modified

**Version informations :**
``` 
- OS: windows 10 (but also possible on MacOS)
- vs code version : 1.52.1
- extension version : 0.3.3
```

[gapoulai](https://profile.intra.42.fr/users/gapoulai)

**Comment by GauthierPoulain** [comment]
but it seems more to be an internal problem with vscode when editing the file by the extension and the easiest way to solve the problem is to change the behavior of the autosave by changing the `files.autoSave`  setting to `onFocusChange`

**Comment by Etheram68** [comment]
Hi, i know this issue, it's a complicated problem, because  when the file is modified, auto-save saves the document so there has been a change, even if you do control-z to go back to zero.

Your solution is indeed the right one, change file.autoSAve setting to onFocusChange
